name: GoldPro V2 Signal Bot

on:
  schedule:
    # 3 تا cron برای اطمینان بیشتر
    - cron: '*/5 * * * *'
    - cron: '2-59/5 * * * *'  
    - cron: '4-59/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run GoldPro
     env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TWELVEDATA_KEY: ${{ secrets.TWELVEDATA_KEY }}
  GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
  GH_PAT: ${{ secrets.GH_PAT }}
  SMSIR_API_KEY: ${{ secrets.SMSIR_API_KEY }}
  SMSIR_LINE_NUMBER: ${{ secrets.SMSIR_LINE_NUMBER }}
  SMSIR_PHONE: ${{ secrets.SMSIR_PHONE }}
        run: python main.py